# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1_left:
    has_velocity_limits: true
    max_velocity: 0.7853981634 
    has_acceleration_limits: true
    max_acceleration: 0.3490658504
  joint1_right:
    has_velocity_limits: true
    max_velocity: 0.7853981634 
    has_acceleration_limits: true
    max_acceleration: 0.3490658504
  joint2_left:
    has_velocity_limits: true
    max_velocity: 0.7853981634 
    has_acceleration_limits: true
    max_acceleration: 0.3490658504
  joint2_right:
    has_velocity_limits: true
    max_velocity: 0.7853981634 
    has_acceleration_limits: true
    max_acceleration: 0.3490658504
  joint3_left:
    has_velocity_limits: true
    max_velocity: 0.7853981634 
    has_acceleration_limits: true
    max_acceleration: 0.3490658504
  joint3_right:
    has_velocity_limits: true
    max_velocity: 0.7853981634 
    has_acceleration_limits: true
    max_acceleration: 0.3490658504
  joint4_left:
    has_velocity_limits: true
    max_velocity: 0.7853981634 
    has_acceleration_limits: true
    max_acceleration: 0.3490658504
  joint4_right:
    has_velocity_limits: true
    max_velocity: 0.7853981634 
    has_acceleration_limits: true
    max_acceleration: 0.3490658504
  joint5_left:
    has_velocity_limits: true
    max_velocity: 0.7853981634 
    has_acceleration_limits: true
    max_acceleration: 0.3490658504
  joint5_right:
    has_velocity_limits: true
    max_velocity: 0.7853981634 
    has_acceleration_limits: true
    max_acceleration: 0.3490658504
  joint6_left:
    has_velocity_limits: true
    max_velocity: 0.7853981634
    has_acceleration_limits: true
    max_acceleration: 0.5235987756
  joint6_right:
    has_velocity_limits: true
    max_velocity: 0.7853981634
    has_acceleration_limits: true
    max_acceleration: 0.5235987756
  joint7_left:
    has_velocity_limits: true
    max_velocity: 0.7853981634
    has_acceleration_limits: true
    max_acceleration: 0.5235987756
  joint7_right:
    has_velocity_limits: true
    max_velocity: 0.7853981634
    has_acceleration_limits: true
    max_acceleration: 0.5235987756
  joint1:
    has_velocity_limits: true
    max_velocity: 0.1745329252
    has_acceleration_limits: true
    max_acceleration: 0.11635528346
  joint2:
    has_velocity_limits: true
    max_velocity: 0.2617993878
    has_acceleration_limits: true
    max_acceleration: 0.1745329252
  joint3:
    has_velocity_limits: true
    max_velocity: 0.3490658504
    has_acceleration_limits: true
    max_acceleration: 0.23271056693
  joint4:
    has_velocity_limits: true
    max_velocity: 3.1415926536
    has_acceleration_limits: true
    max_acceleration: 2.09439510239
