# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_arm_effort_controller:
      type: effort_controllers/JointGroupEffortController

    right_arm_effort_controller:
      type: effort_controllers/JointGroupEffortController

    fold_elevator_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - joint1_left
      - joint2_left
      - joint3_left
      - joint4_left
      - joint5_left
      - joint6_left
      - joint7_left
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false

right_arm_controller:
  ros__parameters:
    joints:
      - joint1_right
      - joint2_right
      - joint3_right
      - joint4_right
      - joint5_right
      - joint6_right
      - joint7_right
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false

left_arm_effort_controller:
  ros__parameters:
    joints:
      - joint1_left
      - joint2_left
      - joint3_left
      - joint4_left
      - joint5_left
      - joint6_left
      - joint7_left

right_arm_effort_controller:
  ros__parameters:
    joints:
      - joint1_right
      - joint2_right
      - joint3_right
      - joint4_right
      - joint5_right
      - joint6_right
      - joint7_right

fold_elevator_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true
    # allow_nonzero_velocity_at_trajectory_end: false
